"""
Event Store Module for SEMS (Series Events Messaging System)

Manages Supabase-based event persistence.
Per Project-Requirements.txt Section 11 (Data Persistence):
- Events stored in Supabase 'events' table
- Events persisted on creation confirmation
- Updates saved immediately on edit confirmation
"""

from typing import Any, List, Optional

from sems.supabase_client import get_client


def create_event(event_data: dict) -> dict:
    """Add event to database with UUID generated by Supabase, return event."""
    client = get_client()
    event = {
        "host_phone": event_data.get("host_phone") or event_data.get("phone_number"),
        "title": event_data.get("title"),
        "description": event_data.get("description"),
        "datetime": event_data.get("datetime"),
        "location": event_data.get("location"),
        "capacity": event_data.get("capacity"),
        "participants": [],
        "status": "open",
        "pending_requests": [],
        "denied_requests": [],
        "private": event_data.get("private", False),
        "invited_phones": [],
        "pending_invites": []
    }
    response = client.table("events").insert(event).execute()
    if response.data and len(response.data) > 0:
        return response.data[0]
    return event


def get_events_by_host(phone: str) -> List[dict]:
    """Filter events by host_phone."""
    client = get_client()
    response = client.table("events").select("*").eq("host_phone", phone).execute()
    return response.data or []


def get_joinable_events(phone: str) -> List[dict]:
    """Get events user can join: exclude own, full, joined, closed, denied."""
    client = get_client()
    # Get all open events
    response = client.table("events").select("*").eq("status", "open").execute()
    events = response.data or []

    joinable = []
    for event in events:
        # Exclude own events
        if event.get("host_phone") == phone:
            continue
        # Exclude already joined
        participants = event.get("participants") or []
        if phone in participants:
            continue
        # Exclude denied requests
        denied = event.get("denied_requests") or []
        if phone in denied:
            continue
        # Exclude full capacity events
        capacity = event.get("capacity")
        if capacity is not None:
            try:
                capacity_int = int(capacity)
                current_count = len(participants)
                if current_count >= capacity_int:
                    continue
            except (ValueError, TypeError):
                pass  # Invalid capacity, treat as unlimited
        joinable.append(event)
    return joinable


def get_joined_events(phone: str) -> List[dict]:
    """Get events where phone is in participants."""
    client = get_client()
    # Use contains operator for array
    response = client.table("events").select("*").contains("participants", [phone]).execute()
    return response.data or []


def get_event_by_id(event_id: str) -> Optional[dict]:
    """Find event by id."""
    client = get_client()
    response = client.table("events").select("*").eq("id", event_id).maybe_single().execute()
    return response.data


def update_event(event_id: str, field: str, value: Any) -> bool:
    """Update event field, return success."""
    client = get_client()
    response = client.table("events").update({field: value}).eq("id", event_id).execute()
    return response.data is not None and len(response.data) > 0


def delete_event(event_id: str) -> bool:
    """Remove event, return success."""
    client = get_client()
    response = client.table("events").delete().eq("id", event_id).execute()
    return response.data is not None and len(response.data) > 0


def join_event(event_id: str, phone: str) -> bool:
    """Add to participants if allowed."""
    client = get_client()
    event = get_event_by_id(event_id)
    if not event:
        return False

    # Cannot join own event
    if event.get("host_phone") == phone:
        return False

    # Cannot join if already joined
    participants = event.get("participants") or []
    if phone in participants:
        return False

    # Cannot join if at capacity
    capacity = event.get("capacity")
    if capacity is not None:
        try:
            capacity_int = int(capacity)
            if len(participants) >= capacity_int:
                return False
        except (ValueError, TypeError):
            pass  # Invalid capacity, treat as unlimited

    # Add participant
    participants.append(phone)
    response = client.table("events").update({"participants": participants}).eq("id", event_id).execute()
    return response.data is not None and len(response.data) > 0


def leave_event(event_id: str, phone: str) -> bool:
    """Remove from participants."""
    client = get_client()
    event = get_event_by_id(event_id)
    if not event:
        return False

    participants = event.get("participants") or []
    if phone not in participants:
        return False

    participants.remove(phone)
    response = client.table("events").update({"participants": participants}).eq("id", event_id).execute()
    return response.data is not None and len(response.data) > 0


def add_pending_request(event_id: str, phone: str) -> bool:
    """Add phone to pending_requests list for event."""
    client = get_client()
    event = get_event_by_id(event_id)
    if not event:
        return False

    pending = event.get("pending_requests") or []
    if phone in pending:
        return False

    pending.append(phone)
    response = client.table("events").update({"pending_requests": pending}).eq("id", event_id).execute()
    return response.data is not None and len(response.data) > 0


def remove_pending_request(event_id: str, phone: str) -> bool:
    """Remove phone from pending_requests list for event."""
    client = get_client()
    event = get_event_by_id(event_id)
    if not event:
        return False

    pending = event.get("pending_requests") or []
    if phone not in pending:
        return False

    pending.remove(phone)
    response = client.table("events").update({"pending_requests": pending}).eq("id", event_id).execute()
    return response.data is not None and len(response.data) > 0


def add_denied_request(event_id: str, phone: str) -> bool:
    """Add phone to denied_requests list for event."""
    client = get_client()
    event = get_event_by_id(event_id)
    if not event:
        return False

    denied = event.get("denied_requests") or []
    if phone in denied:
        return False

    denied.append(phone)
    response = client.table("events").update({"denied_requests": denied}).eq("id", event_id).execute()
    return response.data is not None and len(response.data) > 0


def is_request_pending(event_id: str, phone: str) -> bool:
    """Check if phone has a pending request for event."""
    event = get_event_by_id(event_id)
    if event:
        pending = event.get("pending_requests") or []
        return phone in pending
    return False


def is_request_denied(event_id: str, phone: str) -> bool:
    """Check if phone was denied for event."""
    event = get_event_by_id(event_id)
    if event:
        denied = event.get("denied_requests") or []
        return phone in denied
    return False


def close_event(event_id: str) -> bool:
    """Set event status to closed."""
    return update_event(event_id, "status", "closed")


def get_open_events_for_discovery(phone: str) -> List[dict]:
    """Get events for discovery: open, not own, not full, not joined, not denied, not private (unless invited)."""
    client = get_client()
    response = client.table("events").select("*").eq("status", "open").execute()
    events = response.data or []

    discoverable = []
    for event in events:
        # Exclude own events
        if event.get("host_phone") == phone:
            continue
        # Exclude already joined
        participants = event.get("participants") or []
        if phone in participants:
            continue
        # Exclude denied requests
        denied = event.get("denied_requests") or []
        if phone in denied:
            continue
        # Exclude full capacity events
        capacity = event.get("capacity")
        if capacity is not None:
            try:
                capacity_int = int(capacity)
                current_count = len(participants)
                if current_count >= capacity_int:
                    continue
            except (ValueError, TypeError):
                pass  # Invalid capacity, treat as unlimited
        # Exclude private events unless user is invited
        if event.get("private", False):
            invited = event.get("invited_phones") or []
            pending = event.get("pending_invites") or []
            if phone not in invited and phone not in pending:
                continue
        discoverable.append(event)
    return discoverable


def set_group_chat_id(event_id: str, chat_id: int) -> bool:
    """Set the group_chat_id for an event.

    Args:
        event_id: The event's unique ID
        chat_id: The chat ID from the messaging API

    Returns:
        True if successful, False otherwise
    """
    return update_event(event_id, "group_chat_id", chat_id)


def get_event_by_group_chat_id(chat_id: int) -> Optional[dict]:
    """Find an event by its group_chat_id.

    When multiple events share the same group_chat_id (due to API reusing
    existing chats with same participants), returns the most recently
    closed event.

    Args:
        chat_id: The group chat ID to search for

    Returns:
        The event dict if found, None otherwise
    """
    client = get_client()
    response = client.table("events").select("*").eq("group_chat_id", chat_id).execute()
    matching_events = response.data or []

    if not matching_events:
        return None

    if len(matching_events) == 1:
        return matching_events[0]

    # Multiple events share this chat_id - return the last one (most recent)
    return matching_events[-1]


def get_simulated_days(event_id: str) -> int:
    """Get the cumulative simulated days passed for an event.

    Args:
        event_id: The event's unique ID

    Returns:
        Number of simulated days passed, defaults to 0
    """
    event = get_event_by_id(event_id)
    if event:
        return event.get("simulated_days", 0) or 0
    return 0


def add_simulated_days(event_id: str, days: int) -> int:
    """Add days to the simulated time for an event.

    Args:
        event_id: The event's unique ID
        days: Number of days to add

    Returns:
        New total simulated days
    """
    client = get_client()
    event = get_event_by_id(event_id)
    if not event:
        return 0

    current = event.get("simulated_days", 0) or 0
    new_total = current + days

    response = client.table("events").update({"simulated_days": new_total}).eq("id", event_id).execute()
    if response.data and len(response.data) > 0:
        return new_total
    return 0


def reset_simulated_time(event_id: str) -> bool:
    """Reset simulated time for an event back to 0.

    Args:
        event_id: The event's unique ID

    Returns:
        True if successful, False otherwise
    """
    return update_event(event_id, "simulated_days", 0)


def add_invite(event_id: str, phone: str) -> bool:
    """Add phone to pending_invites list if not already there and not a participant.

    Args:
        event_id: The event's unique ID
        phone: Phone number to invite

    Returns:
        True on success, False if already invited or participant
    """
    client = get_client()
    event = get_event_by_id(event_id)
    if not event:
        return False

    # Check if already a participant
    participants = event.get("participants") or []
    if phone in participants:
        return False

    # Check if already has pending invite
    pending_invites = event.get("pending_invites") or []
    if phone in pending_invites:
        return False

    # Check if already in invited_phones (accepted previously)
    invited_phones = event.get("invited_phones") or []
    if phone in invited_phones:
        return False

    # Add to pending invites
    pending_invites.append(phone)
    response = client.table("events").update({"pending_invites": pending_invites}).eq("id", event_id).execute()
    return response.data is not None and len(response.data) > 0


def get_pending_invites(event_id: str) -> List[str]:
    """Return list of pending invite phone numbers for the event.

    Args:
        event_id: The event's unique ID

    Returns:
        List of phone numbers with pending invites
    """
    event = get_event_by_id(event_id)
    if event:
        return event.get("pending_invites") or []
    return []


def accept_invite(event_id: str, phone: str) -> bool:
    """Accept an invite: remove from pending_invites, add to participants and invited_phones.

    Args:
        event_id: The event's unique ID
        phone: Phone number accepting the invite

    Returns:
        True on success, False if no pending invite
    """
    client = get_client()
    event = get_event_by_id(event_id)
    if not event:
        return False

    pending_invites = event.get("pending_invites") or []
    if phone not in pending_invites:
        return False

    # Remove from pending_invites
    pending_invites.remove(phone)

    # Add to participants
    participants = event.get("participants") or []
    if phone not in participants:
        participants.append(phone)

    # Add to invited_phones for tracking
    invited_phones = event.get("invited_phones") or []
    if phone not in invited_phones:
        invited_phones.append(phone)

    response = client.table("events").update({
        "pending_invites": pending_invites,
        "participants": participants,
        "invited_phones": invited_phones
    }).eq("id", event_id).execute()

    return response.data is not None and len(response.data) > 0


def decline_invite(event_id: str, phone: str) -> bool:
    """Decline an invite: remove from pending_invites.

    Args:
        event_id: The event's unique ID
        phone: Phone number declining the invite

    Returns:
        True on success, False if no pending invite
    """
    client = get_client()
    event = get_event_by_id(event_id)
    if not event:
        return False

    pending_invites = event.get("pending_invites") or []
    if phone not in pending_invites:
        return False

    pending_invites.remove(phone)
    response = client.table("events").update({"pending_invites": pending_invites}).eq("id", event_id).execute()
    return response.data is not None and len(response.data) > 0


def is_invited(event_id: str, phone: str) -> bool:
    """Check if phone is in invited_phones or pending_invites.

    Args:
        event_id: The event's unique ID
        phone: Phone number to check

    Returns:
        True if phone is invited (pending or accepted)
    """
    event = get_event_by_id(event_id)
    if event:
        invited = event.get("invited_phones") or []
        pending = event.get("pending_invites") or []
        return phone in invited or phone in pending
    return False


def has_pending_invite(event_id: str, phone: str) -> bool:
    """Check if phone has a pending invite for the event.

    Args:
        event_id: The event's unique ID
        phone: Phone number to check

    Returns:
        True if phone has a pending invite
    """
    event = get_event_by_id(event_id)
    if event:
        pending = event.get("pending_invites") or []
        return phone in pending
    return False


def get_all_events() -> List[dict]:
    """Return all events.

    Returns:
        List of all event dictionaries
    """
    client = get_client()
    response = client.table("events").select("*").execute()
    return response.data or []
